### ISSUE TITLE
Note field for Seller and Offer

### ISSUE THREAD

**Issue by matteioo** [bresu/buecherboerse#9]
How about adding a note field to the Seller and Offer model?

**Comment by bresu** [comment]
Surely, do have any suggestions for limitations? Also: should this field be searchable with
1. field-search (?note=term)
2. combined-search(?search=term)
I can implement both, but due to the nature of freely written text I can't know what people write in the note. Usually it's something like "Erasmus", "imported from old system" etc. 
That's why I think a field based search makes sense, including it int he combined search is another topic we have to discuss/ think through

**Comment by matteioo** [comment]
The field should probably be `VARCHAR` or something similar with some kind of limitation in characters (100?). As this could be a longer text, searching or filtering for the content wouldn't be helpful. So I'd say neither 1 nor 2.

**Comment by matteioo** [comment]
Addition: field should ideally be optional.

**Comment by bresu** [comment]
Implemented.
